Repository xerial/sqlite-jdbc, pull requests merged in 2022-07, with the labels that each got.

#746 Upgrade to 3.39.2
  Makefile
  VERSION
  docker/dockcross-android-arm
  docker/dockcross-arm64-lts
  docker/dockcross-armv5
  docker/dockcross-armv6
  docker/dockcross-armv6-lts
  docker/dockcross-armv7a-lts
  docker/dockcross-ppc64
  docker/updatescripts.sh
  pom.xml
  src/main/resources/org/sqlite/native/FreeBSD/aarch64/libsqlitejdbc.so
  src/main/resources/org/sqlite/native/FreeBSD/x86/libsqlitejdbc.so
  src/main/resources/org/sqlite/native/FreeBSD/x86_64/libsqlitejdbc.so
  src/main/resources/org/sqlite/native/Linux-Android/aarch64/libsqlitejdbc.so
  src/main/resources/org/sqlite/native/Linux-Android/arm/libsqlitejdbc.so
  src/main/resources/org/sqlite/native/Linux-Android/x86/libsqlitejdbc.so
  src/main/resources/org/sqlite/native/Linux-Android/x86_64/libsqlitejdbc.so
  src/main/resources/org/sqlite/native/Linux-Musl/x86_64/libsqlitejdbc.so
  src/main/resources/org/sqlite/native/Linux/aarch64/libsqlitejdbc.so
  src/main/resources/org/sqlite/native/Linux/arm/libsqlitejdbc.so
  src/main/resources/org/sqlite/native/Linux/armv6/libsqlitejdbc.so
  src/main/resources/org/sqlite/native/Linux/armv7/libsqlitejdbc.so
  src/main/resources/org/sqlite/native/Linux/ppc64/libsqlitejdbc.so
  src/main/resources/org/sqlite/native/Linux/x86/libsqlitejdbc.so
  src/main/resources/org/sqlite/native/Linux/x86_64/libsqlitejdbc.so
  src/main/resources/org/sqlite/native/Mac/aarch64/libsqlitejdbc.jnilib
  src/main/resources/org/sqlite/native/Mac/x86_64/libsqlitejdbc.jnilib
  src/main/resources/org/sqlite/native/Windows/aarch64/sqlitejdbc.dll
  src/main/resources/org/sqlite/native/Windows/armv7/sqlitejdbc.dll
  src/main/resources/org/sqlite/native/Windows/x86/sqlitejdbc.dll
  src/main/resources/org/sqlite/native/Windows/x86_64/sqlitejdbc.dll
Labels: enhancement:SQLite

#704 add native binary for Linux aarch64 with musl
  Makefile
  docker/dockcross-musl-arm64
  src/main/resources/org/sqlite/native/Linux-Musl/aarch64/libsqlitejdbc.so
Labels: platform request

#702 Update changelog for 3.35.0.1 through 3.36.0.3
  README.md
Labels: documentation
